version: "3.9"

services:
  web:
    build: .
    container_name: file_server
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./uploads:/app/${UPLOAD_DIR}
    restart: unless-stopped
